# [[main]]
#   name = "Docs"
#   url = "/docs/prologue/introduction/"
#   weight = 10

# [[main]]
#   name = "Package B"
#   url = "/package_b/kb/article"
#   weight = 10

# [[main]]
#   name = "Package C"
#   url = "/package_c/kb/article"
#   weight = 10
